# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
    -   id: check-builtin-literals
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: detect-private-key
    -   id: fix-encoding-pragma
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-ast
    -   id: debug-statements
    -   id: check-merge-conflict

- repo: https://github.com/ambv/black
  rev: 21.5b1
  hooks:
  - id: black
    language_version: python3.7

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
  - id: mypy

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.5.7
  hooks:
  - id: autopep8

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.8.0
  hooks:
  - id: isort

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.8.0
  hooks:
  - id:  python-no-eval
  - id:  python-use-type-annotations

- repo: https://github.com/asottile/pyupgrade
  rev: v2.18.1
  hooks:
  - id:  pyupgrade

- repo: https://github.com/PyCQA/bandit
  rev: 1.7.0
  hooks:
  - id: bandit

#- repo: https://github.com/PyCQA/pylint
  #rev: v2.8.2
  #hooks:
  #- id: pylint

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.1.0
  hooks:
  - id: detect-secrets
